CREATE TABLE IF NOT EXISTS "jobs" (
  "id"  SERIAL , "name" VARCHAR(255) NOT NULL,
  "status" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
